In [ ]:
import numpy as np

aList = [ "John",33,"Toronto",True]
print(aList)

['John', 33, 'Toronto', True]


# Membuat list dengan menambahkan date

In [1]:
import datetime as dt
tanggal = dt.date.today()
maha_siswa = ["Muhammad Afif Alfatih","2023071005","Prodi Informatika","DAA", str (tanggal), "Universitas Pembangunan Jaya"]
print(maha_siswa)

['Muhammad Afif Alfatih', '2023071005', 'Prodi Informatika', 'DAA', '2024-10-14', 'Universitas Pembangunan Jaya']


# Cetak dengan memanggil urutan ke-n dari list

In [ ]:
print("Nim:", maha_siswa[1])
print("Universitas:", maha_siswa[5])

Nim: 2023071005
Universitas: Universitas Pembangunan Jaya


# List Slicing
Mengambil subset dari elemen list dengan menentukan rentang indeks

In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[2:3]

['Blue']

In [ ]:
maha_siswa[1:3]

['2023071005', 'Prodi Informatika']

# Looping

In [ ]:
for aColor in bin_colors:
  print(aColor+" Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
for mhs in maha_siswa:
  print("UPJ "  + mhs)

UPJ nama
UPJ 2023071005
UPJ Prodi Informatika
UPJ DAA
UPJ 2024-09-19
UPJ Universitas Pembangunan Jaya


# Tuple

In [ ]:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1:]

('Green', 'Blue', 'Yellow')

In [ ]:
tup_upj = ('Universitas','Pembangunan','Jaya')
tup_upj[0:]

('Universitas', 'Pembangunan', 'Jaya')

In [ ]:
nested_tuple = (100, ('200','400','600'),'300',('400', '800'))
nested_tuple[0:1]

(100,)

# Dictionary

In [ ]:
bin_colors={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
bin_colors["refused_color"]

'Red'

In [ ]:
maha_siswa={
    "nama_mhs": "Muhammad Afif Alfatih",
    "nim_mhs": "2023071005",
    "prodi_mhs": "Informatika",
    "univ_mhs": "UPJ"
}
print(maha_siswa)

{'nama_mhs': 'Muhammad Afif Alfatih', 'nim_mhs': '2023071005', 'prodi_mhs': 'Informatika', 'univ_mhs': 'UPJ'}


# Set

In [ ]:
yellow = {'rose','blood','leaves','fire hydrant'}
red = {'leaves','fire hydrant','dandelions'}
print(yellow|red)
print(yellow&red)

{'leaves', 'blood', 'rose', 'dandelions', 'fire hydrant'}
{'leaves', 'fire hydrant'}


# DataFrame

In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1','Informatika','50','30','20'],
    ['2','Sistem Informasi','55','30','25'],
    ['3','Teknik Sipil','40','30','10']
])
print(df)

   0                 1   2   3   4
0  1       Informatika  50  30  20
1  2  Sistem Informasi  55  30  25
2  3      Teknik Sipil  40  30  10


# Transpose Matrix

In [ ]:
import numpy as np
myMatrix = np.array([[100,200,300], [700,600,500],[900,1000,800]])
transpose = np.transpose(myMatrix)
print("Matriks yang ditranspose: ")
print(transpose)

Matriks yang ditranspose: 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
print(type(myMatrix))

<class 'numpy.ndarray'>
